"""Données de seed pour la table ``localites`` (instance Côte d'Ivoire).

Premier lot « localités seules » du moteur dédié Côte d'Ivoire : la racine
continentale, le pays, et les **14 districts** (12 districts + 2 districts
autonomes : Abidjan et Yamoussoukro).

Périmètre et sourçage
---------------------
Ce lot pose la **nomenclature administrative de premier niveau** à partir
d'une source **authoritative et vérifiable** : la norme **ISO 3166-2:CI**
(codes et libellés français officiels, exposés via ``pycountry``). Le champ
``code_administratif_national`` reste ``NULL`` : les sous-codes ISO 3166-2
de la Côte d'Ivoire sont à 2 lettres (``AB``, ``BS`` …) et ne satisfont pas
la contrainte ``^[A-Z]{3}$`` de la colonne (convention de code national à
3 lettres, cf. le décret guinéen sur l'instance Guinée) ; le sous-code ISO
est porté dans ``notes``.

Densification sourcée (passe 2)
-------------------------------
Les 14 districts sont désormais **densifiés en passe sourcée** (accès réseau)
selon la doctrine « aucune coordonnée inventée » :

* **Coordonnées** (``latitude`` / ``longitude``) : point représentatif de
  l'entité *district* correspondante sur **Wikidata** (propriété ``P625``).
  Le QID de l'entité district est cité dans ``notes`` pour la traçabilité.
  Les deux districts autonomes utilisent l'entité *district autonome*
  (Q19830972 Abidjan, Q19830973 Yamoussoukro), distincte de l'entité ville.
  **Règle de sélection déterministe** quand ``P625`` porte plusieurs
  valeurs (cf. ADR-0006) : on retient le statement de rang ``preferred``
  s'il existe, sinon le premier statement dans l'ordre document Wikidata
  parmi les rangs ``normal``. Trois entités sont concernées : ``CI-SV``
  (Savanes) tranchée par le rang ``preferred`` ; ``CI-VB`` (Vallée du
  Bandama) et ``CI-DN`` (Denguélé) par l'ordre document (deux statements
  ``normal`` équivalents).
* **Population** (``population_estimee`` / ``annee_population`` = 2021) :
  **RGPH 2021** (5ᵉ Recensement Général de la Population et de l'Habitat,
  INS Côte d'Ivoire). Le total par district est l'agrégat des comptages
  régionaux officiels publiés par l'INS
  (https://www.ins.ci/RGPH2021/RGPH2021-RESULTATS%20GLOBAUX_VF.pdf) ;
  contre-vérifié : Abidjan, Yamoussoukro et Zanzan concordent exactement
  avec les valeurs datées 2021 de Wikidata, le total national reconstitué
  vaut ~29,39 millions (chiffre officiel RGPH 2021 : 29 389 150). Étant un
  agrégat reconstruit (le PDF INS n'étant pas récupérable en ligne), chaque
  total porte une incertitude de l'ordre de ±quelques unités face au chiffre
  district primaire.
* **Chef-lieu** de district : capitale administrative de l'entité district
  sur Wikidata (propriété ``P36``, rang ``normal`` ; les 14 valeurs ont été
  résolues et concordent avec le décret 2011-263), portée dans ``notes``.

L'``altitude_metres`` reste ``NULL`` : une région administrative n'a pas
d'altitude ponctuelle univoque ; aucune valeur n'est inventée.

Le pays ``civ`` est lui aussi densifié : centroïde Wikidata Q1008 (``P625``)
et population nationale RGPH 2021 (29 389 150 hab.), chiffre officiel absent
de Wikidata mais recoupé par la somme des 14 districts. La racine
continentale ``afrique`` conserve son sourçage initial (entité structurelle,
sans centroïde).

Régions (niveau ``prefecture``)
-------------------------------
Les **31 régions** actuelles (réforme de 2011) sont ajoutées au niveau
générique ``prefecture`` (cf. ADR-0005 : ``type_localite`` est un axe
technique, l'identité ivoirienne reste dans ``nom`` / ``notes``). Chaque
région est rattachée à son **district parent** (relation Wikidata ``P131``),
avec coordonnées Wikidata (``P625``, règle de sélection de l'ADR-0006),
chef-lieu, et population **RGPH 2021** (INS) dont la somme par district
reproduit exactement le total du district. Réserves documentées en ``notes`` :

* **N'Zi** et **La Mé** : population non recoupée par Wikidata (mono-sourcée
  RGPH/Wikipédia) ;
* **Hambol** : le point ``P625`` de l'entité région est erroné sur Wikidata
  (co-localisé avec Bouaké) ; on retient la coordonnée du chef-lieu Katiola ;
* **Codes ISO 3166-2** : la révision 2020 a supprimé les codes de niveau
  région ; les 5 anciens codes encore présents (CI-02, CI-12, CI-13, CI-14,
  CI-17) sont portés en ``notes`` avec la mention « périmé », jamais comme
  code courant.

Départements (niveau ``commune``)
---------------------------------
Les **111 départements** actuels sont ajoutés au niveau générique ``commune``
(cf. ADR-0005) : **108** rattachés à une région (``prefecture``) et **3** aux
districts autonomes (Abidjan, Yamoussoukro), ces derniers sans région
intermédiaire (``commune`` -> ``region_administrative``, autorisé par la
matrice hiérarchique). Rattachement Wikidata ``P131`` ; le cas **Kani ->
Worodougou** comble une lacune ``P131`` amont (fait sourcé). Coordonnées
Wikidata ``P625`` (règle ADR-0006 ; **Attiégouakro**, sans ``P625`` propre,
prend la coordonnée de son chef-lieu). Aucun département n'a de code
ISO 3166-2 (standard limité aux districts). Sont écartés les **6 anciens
départements dissous** (Est, Nord, Ouest, Sud, Centre, Centre-Ouest, sans
``P131``).

**Population RGPH 2021** (INS Côte d'Ivoire) : chaque département porte sa
population du recensement 2021, sourcée via le portail open data officiel
``data.gouv.ci`` et le miroir homogène ``citypopulation.de`` (``ins.ci`` étant
bloqué). Contrôle d'intégrité : la somme des départements reproduit le total
de chaque région déjà gravée (écart ≤ 1 hab) et le total national vaut
**29 389 150** hab. (chiffre officiel exact).

Deux libellés issus de la migration 0007 sont **corrigés** ici : ``Oumé``
(ex ``d'Oumé`` — le ``d'`` élidé n'avait pas été retiré ; code désormais
``civ_dep_oume``) et ``Niakaramandougou`` (orthographe officielle, ex
``Niakaramadougou`` fidèle à Wikidata ; code ``civ_dep_niakaramandougou``).
"""

from __future__ import annotations

from typing import Any

# Source primaire de la population (réemployée dans chaque note de district).
_SOURCE_RGPH: str = "RGPH 2021 (INS Côte d'Ivoire), agrégat des régions"


def _district(
    code: str,
    nom: str,
    iso_3166_2: str,
    latitude: float,
    longitude: float,
    population_2021: int,
    chef_lieu: str,
    wikidata_qid: str,
    *,
    autonome: bool = False,
) -> dict[str, Any]:
    """Construit une entrée ``region_administrative`` densifiée pour un district CIV.

    Coordonnées : point représentatif Wikidata (``P625``) de l'entité district.
    Population : total RGPH 2021 (INS). Chef-lieu et QID portés dans ``notes``.
    """
    qualif = "District autonome" if autonome else "District"
    notes = (
        f"{qualif} de Côte d'Ivoire (ISO 3166-2 : {iso_3166_2}). "
        f"Chef-lieu : {chef_lieu}. "
        f"Population {population_2021} hab. — {_SOURCE_RGPH}. "
        f"Coordonnées : point représentatif Wikidata {wikidata_qid} (P625). "
        f"Libellé et code issus de la norme ISO 3166-2:CI."
    )
    return {
        "code": code,
        "nom": nom,
        "type_localite": "region_administrative",
        "parent_code": "civ",
        "pays_iso3": "CIV",
        "latitude": latitude,
        "longitude": longitude,
        "altitude_metres": None,
        "population_estimee": population_2021,
        "annee_population": 2021,
        "fuseau_horaire": "Africa/Abidjan",
        "notes": notes,
    }


# Libellé du district parent, réemployé dans les notes des régions.
_DISTRICT_NOM: dict[str, str] = {
    "civ_bas_sassandra": "Bas-Sassandra",
    "civ_comoe": "Comoé",
    "civ_denguele": "Denguélé",
    "civ_goh_djiboua": "Gôh-Djiboua",
    "civ_lacs": "Lacs",
    "civ_lagunes": "Lagunes",
    "civ_montagnes": "Montagnes",
    "civ_sassandra_marahoue": "Sassandra-Marahoué",
    "civ_savanes": "Savanes",
    "civ_vallee_du_bandama": "Vallée du Bandama",
    "civ_woroba": "Woroba",
    "civ_zanzan": "Zanzan",
}


def _region(
    code: str,
    nom: str,
    parent_code: str,
    wikidata_qid: str,
    latitude: float,
    longitude: float,
    chef_lieu: str,
    population_2021: int,
    iso_perime: str | None,
    coord_chef_lieu: bool,
    mono_source: bool,
) -> dict[str, Any]:
    """Construit une entrée ``prefecture`` (région ivoirienne) rattachée à son district.

    Le niveau générique ``prefecture`` porte la région ivoirienne (cf.
    ADR-0005) ; ``type_localite`` n'est pas le nom du palier réel, l'identité
    est dans ``nom`` / ``notes``. Coordonnées : point Wikidata (``P625``) sauf
    repli documenté (``coord_chef_lieu``). Population : RGPH 2021 (INS).
    """
    mono = (
        " Population non recoupée par Wikidata (mono-sourcée RGPH/Wikipédia)."
        if mono_source
        else ""
    )
    if coord_chef_lieu:
        coord_line = (
            f"Coordonnées : repli sur le chef-lieu {chef_lieu} (Wikidata) — le "
            f"point P625 de l'entité région {wikidata_qid} est erroné (co-localisé "
            f"avec le district)."
        )
    else:
        coord_line = f"Coordonnées : point représentatif Wikidata {wikidata_qid} (P625)."
    iso_line = (
        f" Ancien code ISO 3166-2 (système pré-2020, périmé) : {iso_perime}." if iso_perime else ""
    )
    notes = (
        f"Région de Côte d'Ivoire (niveau générique « prefecture » ; district "
        f"parent : {_DISTRICT_NOM[parent_code]}). Chef-lieu : {chef_lieu}. "
        f"Population {population_2021} hab. — RGPH 2021 (INS Côte d'Ivoire).{mono} "
        f"{coord_line}{iso_line}"
    )
    return {
        "code": code,
        "nom": nom,
        "type_localite": "prefecture",
        "parent_code": parent_code,
        "pays_iso3": "CIV",
        "latitude": float(latitude),
        "longitude": float(longitude),
        "altitude_metres": None,
        "population_estimee": population_2021,
        "annee_population": 2021,
        "fuseau_horaire": "Africa/Abidjan",
        "notes": notes,
    }


# 31 régions actuelles (réforme 2011), rattachées à leur district par Wikidata
# P131 ; population RGPH 2021 (somme exacte = total du district parent).
# Tuple : (code, nom, district_parent, QID, lat, lon, chef-lieu, pop_2021,
#          ancien_code_iso_périmé | None, coord_repli_chef_lieu, pop_mono_sourcée)
_REGIONS_DATA: tuple[tuple[Any, ...], ...] = (
    (
        "civ_gbokle",
        "Gbôklé",
        "civ_bas_sassandra",
        "Q22080829",
        4.95,
        -6.08333333,
        "Sassandra",
        460980,
        None,
        False,
        False,
    ),
    (
        "civ_nawa",
        "Nawa",
        "civ_bas_sassandra",
        "Q22080902",
        5.78333333,
        -6.6,
        "Soubré",
        1165472,
        None,
        False,
        False,
    ),
    (
        "civ_san_pedro",
        "San-Pédro",
        "civ_bas_sassandra",
        "Q22080959",
        4.75,
        -6.63333333,
        "San-Pédro",
        1060724,
        None,
        False,
        False,
    ),
    (
        "civ_indenie_djuablin",
        "Indénié-Djuablin",
        "civ_comoe",
        "Q16643482",
        6.73333333,
        -3.48333333,
        "Abengourou",
        716443,
        None,
        False,
        False,
    ),
    (
        "civ_sud_comoe",
        "Sud-Comoé",
        "civ_comoe",
        "Q842495",
        5.5,
        -3.25,
        "Aboisso",
        784893,
        "CI-13",
        False,
        False,
    ),
    (
        "civ_folon",
        "Folon",
        "civ_denguele",
        "Q3075118",
        10.0,
        -7.83333333,
        "Minignan",
        146209,
        None,
        False,
        False,
    ),
    (
        "civ_kabadougou",
        "Kabadougou",
        "civ_denguele",
        "Q24756897",
        9.5,
        -7.56666667,
        "Odienné",
        289806,
        None,
        False,
        False,
    ),
    (
        "civ_goh",
        "Gôh",
        "civ_goh_djiboua",
        "Q24754296",
        6.13333333,
        -5.93333333,
        "Gagnoa",
        985282,
        None,
        False,
        False,
    ),
    (
        "civ_loh_djiboua",
        "Lôh-Djiboua",
        "civ_goh_djiboua",
        "Q21084295",
        5.83333333,
        -5.36666667,
        "Divo",
        1103158,
        None,
        False,
        False,
    ),
    (
        "civ_belier",
        "Bélier",
        "civ_lacs",
        "Q19677085",
        6.92,
        -5.05,
        "Toumodi",
        415593,
        None,
        False,
        False,
    ),
    (
        "civ_iffou",
        "Iffou",
        "civ_lacs",
        "Q21082947",
        7.25,
        -3.86666667,
        "Daoukro",
        378560,
        None,
        False,
        False,
    ),
    (
        "civ_moronou",
        "Moronou",
        "civ_lacs",
        "Q20743715",
        6.65,
        -4.2,
        "Bongouanou",
        439755,
        None,
        False,
        False,
    ),
    (
        "civ_n_zi",
        "N'Zi",
        "civ_lacs",
        "Q22080918",
        6.65,
        -4.7,
        "Dimbokro",
        254623,
        None,
        False,
        True,
    ),
    (
        "civ_agneby_tiassa",
        "Agnéby-Tiassa",
        "civ_lagunes",
        "Q16525480",
        6.0,
        -4.0,
        "Agboville",
        865951,
        None,
        False,
        False,
    ),
    (
        "civ_grands_ponts",
        "Grands-Ponts",
        "civ_lagunes",
        "Q22080838",
        5.31666667,
        -4.38333333,
        "Dabou",
        450007,
        None,
        False,
        False,
    ),
    (
        "civ_la_me",
        "La Mé",
        "civ_lagunes",
        "Q17638767",
        6.16666667,
        -3.98333333,
        "Adzopé",
        726665,
        None,
        False,
        True,
    ),
    (
        "civ_cavally",
        "Cavally",
        "civ_montagnes",
        "Q20641894",
        6.53333333,
        -7.48333333,
        "Guiglo",
        708241,
        None,
        False,
        False,
    ),
    (
        "civ_guemon",
        "Guémon",
        "civ_montagnes",
        "Q21082912",
        6.41666667,
        -7.5,
        "Duékoué",
        930873,
        None,
        False,
        False,
    ),
    (
        "civ_tonkpi",
        "Tonkpi",
        "civ_montagnes",
        "Q17355578",
        7.4,
        -7.55,
        "Man",
        1387909,
        None,
        False,
        False,
    ),
    (
        "civ_haut_sassandra",
        "Haut-Sassandra",
        "civ_sassandra_marahoue",
        "Q845709",
        7.0,
        -6.5,
        "Daloa",
        1739697,
        "CI-02",
        False,
        False,
    ),
    (
        "civ_marahoue",
        "Marahoué",
        "civ_sassandra_marahoue",
        "Q839083",
        7.16666667,
        -5.83333333,
        "Bouaflé",
        981180,
        "CI-12",
        False,
        False,
    ),
    (
        "civ_bagoue",
        "Bagoué",
        "civ_savanes",
        "Q2879161",
        9.51666667,
        -6.48333333,
        "Boundiali",
        515890,
        None,
        False,
        False,
    ),
    (
        "civ_poro",
        "Poro",
        "civ_savanes",
        "Q22080932",
        9.41666667,
        -5.61666667,
        "Korhogo",
        1040461,
        None,
        False,
        False,
    ),
    (
        "civ_tchologo",
        "Tchologo",
        "civ_savanes",
        "Q17355495",
        9.58333333,
        -5.18333333,
        "Ferkessédougou",
        603084,
        None,
        False,
        False,
    ),
    (
        "civ_gbeke",
        "Gbêkê",
        "civ_vallee_du_bandama",
        "Q22080826",
        7.68333333,
        -5.01666667,
        "Bouaké",
        1352900,
        None,
        False,
        False,
    ),
    (
        "civ_hambol",
        "Hambol",
        "civ_vallee_du_bandama",
        "Q21082919",
        8.13333333,
        -5.1,
        "Katiola",
        612029,
        None,
        True,
        False,
    ),
    (
        "civ_bafing",
        "Bafing",
        "civ_woroba",
        "Q799800",
        8.5,
        -7.5,
        "Touba",
        262850,
        "CI-17",
        False,
        False,
    ),
    (
        "civ_bere",
        "Béré",
        "civ_woroba",
        "Q22080753",
        8.06666667,
        -6.18333333,
        "Mankono",
        492151,
        None,
        False,
        False,
    ),
    (
        "civ_worodougou",
        "Worodougou",
        "civ_woroba",
        "Q846056",
        8.5,
        -6.33333333,
        "Séguéla",
        429812,
        "CI-14",
        False,
        False,
    ),
    (
        "civ_bounkani",
        "Bounkani",
        "civ_zanzan",
        "Q19830823",
        9.26666667,
        -3.0,
        "Bouna",
        427037,
        None,
        False,
        False,
    ),
    (
        "civ_gontougo",
        "Gontougo",
        "civ_zanzan",
        "Q17355494",
        8.03333333,
        -2.78333333,
        "Bondoukou",
        917828,
        None,
        False,
        False,
    ),
)


def _departement(
    code: str,
    nom: str,
    parent_code: str,
    parent_nom: str,
    wikidata_qid: str,
    latitude: float,
    longitude: float,
    chef_lieu: str,
    coord_mode: str,
    chef_infere: bool,
    population_2021: int,
) -> dict[str, Any]:
    """Construit une entrée ``commune`` (département ivoirien) rattachée à son parent.

    Le niveau générique ``commune`` porte le département (cf. ADR-0005). Le
    parent est une région (``prefecture``) ou, pour les départements des
    districts autonomes, le district lui-même (``region_administrative``) —
    les deux sont autorisés par la matrice hiérarchique. Coordonnées : point
    Wikidata ``P625`` (règle de rang ADR-0006), avec repli chef-lieu documenté.
    Population : **RGPH 2021** (INS Côte d'Ivoire), sourcée via data.gouv.ci /
    citypopulation.de ; la somme par région reproduit le total régional (±1).
    """
    coord_txt = {
        "u": f"point représentatif Wikidata {wikidata_qid} (P625)",
        "p": f"point Wikidata {wikidata_qid} (P625, rang preferred)",
        "d": f"point Wikidata {wikidata_qid} (P625, 1er statement normal, cf. ADR-0006)",
        "r": (
            f"repli sur le chef-lieu {chef_lieu} (Wikidata) — département sans P625 "
            f"propre (cf. ADR-0006)"
        ),
    }[coord_mode]
    chef_txt = f"Chef-lieu : {chef_lieu}" + (
        " (inféré du toponyme, P36 absent sur Wikidata)" if chef_infere else ""
    )
    notes = (
        f"Département de Côte d'Ivoire (niveau générique « commune » ; parent : "
        f"{parent_nom}). {chef_txt}. Coordonnées : {coord_txt}. Population "
        f"{population_2021} hab. — RGPH 2021 (INS Côte d'Ivoire). Aucun code "
        f"ISO 3166-2 (standard limité aux districts)."
    )
    return {
        "code": code,
        "nom": nom,
        "type_localite": "commune",
        "parent_code": parent_code,
        "pays_iso3": "CIV",
        "latitude": float(latitude),
        "longitude": float(longitude),
        "altitude_metres": None,
        "population_estimee": population_2021,
        "annee_population": 2021,
        "fuseau_horaire": "Africa/Abidjan",
        "notes": notes,
    }


# 111 départements actuels : 108 rattachés à une région (``prefecture``) + 3 aux
# districts autonomes (Abidjan, Yamoussoukro) faute de régions. Rattachement
# Wikidata P131 (Kani -> Worodougou sourcé, lacune P131 amont). Coordonnées P625
# (règle ADR-0006 ; Attiégouakro : repli chef-lieu, sans P625). Population RGPH
# 2021 (INS, via data.gouv.ci / citypopulation.de ; somme par région = total
# régional à ±1 hab, national = 29 389 150 exact).
# Corrections de noms vs migration 0007 : « Oumé » (ex « d'Oumé », code
# civ_dep_oume) et « Niakaramandougou » (orthographe officielle, ex
# « Niakaramadougou », code civ_dep_niakaramandougou).
# Tuple : (code, nom, parent_code, parent_nom, QID, lat, lon, chef-lieu,
#          coord_mode {u:unique, p:preferred, d:1er normal, r:repli}, chef_infere,
#          population_2021)
_DEPARTEMENTS_DATA: tuple[tuple[Any, ...], ...] = (
    (
        "civ_dep_fresco",
        "Fresco",
        "civ_gbokle",
        "Gbôklé",
        "Q5502908",
        5.08333333,
        -5.56666667,
        "Fresco",
        "u",
        False,
        107752,
    ),
    (
        "civ_dep_sassandra",
        "Sassandra",
        "civ_gbokle",
        "Gbôklé",
        "Q7425755",
        4.95,
        -6.08333333,
        "Sassandra",
        "u",
        False,
        353228,
    ),
    (
        "civ_dep_buyo",
        "Buyo",
        "civ_nawa",
        "Nawa",
        "Q22080311",
        6.23333333,
        -7.05,
        "Buyo",
        "u",
        False,
        176568,
    ),
    (
        "civ_dep_gueyo",
        "Guéyo",
        "civ_nawa",
        "Nawa",
        "Q5623153",
        5.68333333,
        -6.06666667,
        "Guéyo",
        "u",
        False,
        102213,
    ),
    (
        "civ_dep_meagui",
        "Méagui",
        "civ_nawa",
        "Nawa",
        "Q22080529",
        5.4,
        -6.56666667,
        "Méagui",
        "u",
        False,
        299251,
    ),
    (
        "civ_dep_soubre",
        "Soubré",
        "civ_nawa",
        "Nawa",
        "Q23020526",
        5.78333333,
        -6.6,
        "Soubré",
        "d",
        False,
        587441,
    ),
    (
        "civ_dep_san_pedro",
        "San-Pédro",
        "civ_san_pedro",
        "San-Pédro",
        "Q16884075",
        5.0,
        -6.75,
        "San-Pédro",
        "u",
        False,
        790242,
    ),
    (
        "civ_dep_tabou",
        "Tabou",
        "civ_san_pedro",
        "San-Pédro",
        "Q3513531",
        4.42,
        -7.36,
        "Tabou",
        "u",
        False,
        270482,
    ),
    (
        "civ_dep_abengourou",
        "Abengourou",
        "civ_indenie_djuablin",
        "Indénié-Djuablin",
        "Q4666747",
        6.73333333,
        -3.48333333,
        "Abengourou",
        "d",
        False,
        430539,
    ),
    (
        "civ_dep_agnibilekrou",
        "Agnibilékrou",
        "civ_indenie_djuablin",
        "Indénié-Djuablin",
        "Q4693215",
        7.21666667,
        -3.33333333,
        "Agnibilékrou",
        "u",
        False,
        216264,
    ),
    (
        "civ_dep_bettie",
        "Bettié",
        "civ_indenie_djuablin",
        "Indénié-Djuablin",
        "Q4898648",
        6.06666667,
        -3.4,
        "Bettié",
        "u",
        False,
        69640,
    ),
    (
        "civ_dep_aboisso",
        "Aboisso",
        "civ_sud_comoe",
        "Sud-Comoé",
        "Q3445349",
        5.46666667,
        -3.2,
        "Aboisso",
        "p",
        False,
        361842,
    ),
    (
        "civ_dep_adiake",
        "Adiaké",
        "civ_sud_comoe",
        "Sud-Comoé",
        "Q4682641",
        5.28333333,
        -3.3,
        "Adiaké",
        "d",
        False,
        88006,
    ),
    (
        "civ_dep_grand_bassam",
        "Grand-Bassam",
        "civ_sud_comoe",
        "Sud-Comoé",
        "Q5594198",
        5.2,
        -3.73333333,
        "Grand-Bassam",
        "d",
        False,
        267103,
    ),
    (
        "civ_dep_tiapoum",
        "Tiapoum",
        "civ_sud_comoe",
        "Sud-Comoé",
        "Q7800274",
        5.13333333,
        -3.01666667,
        "Tiapoum",
        "u",
        False,
        67941,
    ),
    (
        "civ_dep_kaniasso",
        "Kaniasso",
        "civ_folon",
        "Folon",
        "Q22080865",
        9.81666667,
        -7.51666667,
        "Kaniasso",
        "u",
        False,
        84572,
    ),
    (
        "civ_dep_minignan",
        "Minignan",
        "civ_folon",
        "Folon",
        "Q6865254",
        10.0,
        -7.83333333,
        "Minignan",
        "u",
        False,
        61637,
    ),
    (
        "civ_dep_gbeleban",
        "Gbéléban",
        "civ_kabadougou",
        "Kabadougou",
        "Q22080400",
        9.58333333,
        -8.13333333,
        "Gbéléban",
        "u",
        False,
        29532,
    ),
    (
        "civ_dep_madinani",
        "Madinani",
        "civ_kabadougou",
        "Kabadougou",
        "Q13125232",
        9.61666667,
        -6.95,
        "Madinani",
        "u",
        False,
        50248,
    ),
    (
        "civ_dep_odienne",
        "Odienné",
        "civ_kabadougou",
        "Kabadougou",
        "Q7077786",
        9.5,
        -7.56666667,
        "Odienné",
        "u",
        False,
        156730,
    ),
    (
        "civ_dep_samatiguila",
        "Samatiguila",
        "civ_kabadougou",
        "Kabadougou",
        "Q22080957",
        9.81666667,
        -7.56666667,
        "Samatiguila",
        "u",
        False,
        19710,
    ),
    (
        "civ_dep_seguelon",
        "Séguélon",
        "civ_kabadougou",
        "Kabadougou",
        "Q22080637",
        9.35,
        -7.11666667,
        "Séguélon",
        "u",
        False,
        33585,
    ),
    (
        "civ_dep_oume",
        "Oumé",
        "civ_goh",
        "Gôh",
        "Q7110509",
        6.38333333,
        -5.41666667,
        "Oumé",
        "u",
        False,
        260786,
    ),
    (
        "civ_dep_gagnoa",
        "Gagnoa",
        "civ_goh",
        "Gôh",
        "Q998640",
        6.13638889,
        -5.95805556,
        "Gagnoa",
        "d",
        False,
        724496,
    ),
    (
        "civ_dep_divo",
        "Divo",
        "civ_loh_djiboua",
        "Lôh-Djiboua",
        "Q5284660",
        5.83333333,
        -5.36666667,
        "Divo",
        "u",
        False,
        571688,
    ),
    (
        "civ_dep_guitry",
        "Guitry",
        "civ_loh_djiboua",
        "Lôh-Djiboua",
        "Q5616918",
        5.51666667,
        -5.23333333,
        "Guitry",
        "u",
        False,
        197236,
    ),
    (
        "civ_dep_lakota",
        "Lakota",
        "civ_loh_djiboua",
        "Lôh-Djiboua",
        "Q3216495",
        5.85,
        -5.68333333,
        "Lakota",
        "u",
        False,
        334235,
    ),
    (
        "civ_dep_didievi",
        "Didiévi",
        "civ_belier",
        "Bélier",
        "Q5274201",
        7.13333333,
        -4.9,
        "Didiévi",
        "u",
        False,
        93629,
    ),
    (
        "civ_dep_djekanou",
        "Djékanou",
        "civ_belier",
        "Bélier",
        "Q22080359",
        6.48333333,
        -5.11666667,
        "Djékanou",
        "u",
        False,
        37281,
    ),
    (
        "civ_dep_tiebissou",
        "Tiébissou",
        "civ_belier",
        "Bélier",
        "Q3530008",
        7.27,
        -5.48,
        "Tiébissou",
        "u",
        False,
        116321,
    ),
    (
        "civ_dep_toumodi",
        "Toumodi",
        "civ_belier",
        "Bélier",
        "Q3532935",
        6.92,
        -5.05,
        "Toumodi",
        "u",
        False,
        168363,
    ),
    (
        "civ_dep_daoukro",
        "Daoukro",
        "civ_iffou",
        "Iffou",
        "Q10977853",
        7.25,
        -3.86666667,
        "Daoukro",
        "d",
        False,
        148095,
    ),
    (
        "civ_dep_m_bahiakro",
        "M’Bahiakro",
        "civ_iffou",
        "Iffou",
        "Q20625104",
        7.46666667,
        -4.33333333,
        "M'bahiakro",
        "d",
        False,
        78369,
    ),
    (
        "civ_dep_ouelle",
        "Ouellé",
        "civ_iffou",
        "Iffou",
        "Q106634226",
        7.3,
        -4.01666667,
        "Ouellé",
        "u",
        False,
        56501,
    ),
    (
        "civ_dep_prikro",
        "Prikro",
        "civ_iffou",
        "Iffou",
        "Q7242983",
        7.63333333,
        -3.98333333,
        "Prikro",
        "u",
        False,
        95595,
    ),
    (
        "civ_dep_arrah",
        "Arrah",
        "civ_moronou",
        "Moronou",
        "Q22080747",
        6.66666667,
        -3.96666667,
        "Arrah",
        "u",
        False,
        103846,
    ),
    (
        "civ_dep_bongouanou",
        "Bongouanou",
        "civ_moronou",
        "Moronou",
        "Q4941915",
        6.65,
        -4.2,
        "Bongouanou",
        "d",
        False,
        193158,
    ),
    (
        "civ_dep_m_batto",
        "M’Batto",
        "civ_moronou",
        "Moronou",
        "Q22080890",
        6.46666667,
        -4.36666667,
        "M’batto",
        "u",
        False,
        142750,
    ),
    (
        "civ_dep_bocanda",
        "Bocanda",
        "civ_n_zi",
        "N'Zi",
        "Q4936144",
        7.06666667,
        -4.5,
        "Bocanda",
        "d",
        False,
        121469,
    ),
    (
        "civ_dep_dimbokro",
        "Dimbokro",
        "civ_n_zi",
        "N'Zi",
        "Q5277184",
        6.65,
        -4.7,
        "Dimbokro",
        "u",
        False,
        102192,
    ),
    (
        "civ_dep_kouassi_kouassikro",
        "Kouassi-Kouassikro",
        "civ_n_zi",
        "N'Zi",
        "Q22080489",
        7.01666667,
        -4.71666667,
        "Kouassi Kouassikro",
        "u",
        False,
        30962,
    ),
    (
        "civ_dep_agboville",
        "Agboville",
        "civ_agneby_tiassa",
        "Agnéby-Tiassa",
        "Q4691668",
        5.93333333,
        -4.21666667,
        "Agboville",
        "u",
        False,
        384340,
    ),
    (
        "civ_dep_sikensi",
        "Sikensi",
        "civ_agneby_tiassa",
        "Agnéby-Tiassa",
        "Q11057455",
        5.66666667,
        -4.56666667,
        "Sikensi",
        "u",
        False,
        125897,
    ),
    (
        "civ_dep_taabo",
        "Taabo",
        "civ_agneby_tiassa",
        "Agnéby-Tiassa",
        "Q22000943",
        6.23333333,
        -5.13333333,
        "Taabo",
        "u",
        False,
        76761,
    ),
    (
        "civ_dep_tiassale",
        "Tiassalé",
        "civ_agneby_tiassa",
        "Agnéby-Tiassa",
        "Q3528067",
        5.9,
        -4.83333333,
        "Tiassalé",
        "u",
        False,
        278954,
    ),
    (
        "civ_dep_dabou",
        "Dabou",
        "civ_grands_ponts",
        "Grands-Ponts",
        "Q5207537",
        5.31666667,
        -4.38333333,
        "Dabou",
        "u",
        False,
        213582,
    ),
    (
        "civ_dep_grand_lahou",
        "Grand-Lahou",
        "civ_grands_ponts",
        "Grands-Ponts",
        "Q5594719",
        5.13333333,
        -5.01666667,
        "Grand-Lahou",
        "u",
        False,
        155832,
    ),
    (
        "civ_dep_jacqueville",
        "Jacqueville",
        "civ_grands_ponts",
        "Grands-Ponts",
        "Q3160383",
        5.15,
        -4.4,
        "Jacqueville",
        "u",
        False,
        80593,
    ),
    (
        "civ_dep_adzope",
        "Adzopé",
        "civ_la_me",
        "La Mé",
        "Q263616",
        6.1058336,
        -3.8640409,
        "Adzopé",
        "p",
        False,
        283727,
    ),
    (
        "civ_dep_akoupe",
        "Akoupé",
        "civ_la_me",
        "La Mé",
        "Q4701559",
        6.38333333,
        -3.9,
        "Akoupé",
        "u",
        False,
        156698,
    ),
    (
        "civ_dep_alepe",
        "Alépé",
        "civ_la_me",
        "La Mé",
        "Q4738854",
        5.5,
        -3.66666667,
        "Alépé",
        "u",
        False,
        180253,
    ),
    (
        "civ_dep_yakasse_attobrou",
        "Yakassé-Attobrou",
        "civ_la_me",
        "La Mé",
        "Q8047054",
        6.18333333,
        -3.65,
        "Yakassé-Attobrou",
        "u",
        False,
        105986,
    ),
    (
        "civ_dep_blolequin",
        "Bloléquin",
        "civ_cavally",
        "Cavally",
        "Q390288",
        6.56666667,
        -8.0,
        "Bloléquin",
        "u",
        False,
        237944,
    ),
    (
        "civ_dep_guiglo",
        "Guiglo",
        "civ_cavally",
        "Cavally",
        "Q5615685",
        6.55,
        -7.48333333,
        "Guiglo",
        "u",
        False,
        259381,
    ),
    (
        "civ_dep_tai",
        "Taï",
        "civ_cavally",
        "Cavally",
        "Q22080653",
        5.86666667,
        -7.45,
        "Taï",
        "u",
        False,
        117387,
    ),
    (
        "civ_dep_toulepleu",
        "Toulépleu",
        "civ_cavally",
        "Cavally",
        "Q6582823",
        6.58,
        -8.42,
        "Toulepleu",
        "u",
        False,
        93529,
    ),
    (
        "civ_dep_bangolo",
        "Bangolo",
        "civ_guemon",
        "Guémon",
        "Q4855522",
        7.01666667,
        -7.48333333,
        "Bangolo",
        "u",
        False,
        270629,
    ),
    (
        "civ_dep_duekoue",
        "Duékoué",
        "civ_guemon",
        "Guémon",
        "Q5317693",
        6.73333333,
        -7.35,
        "Duékoué",
        "u",
        False,
        420911,
    ),
    (
        "civ_dep_facobly",
        "Facobly",
        "civ_guemon",
        "Guémon",
        "Q22080388",
        7.38333333,
        -7.38333333,
        "Facobly",
        "u",
        False,
        94610,
    ),
    (
        "civ_dep_kouibly",
        "Kouibly",
        "civ_guemon",
        "Guémon",
        "Q6434511",
        7.25,
        -7.23333333,
        "Kouibly",
        "u",
        False,
        144723,
    ),
    (
        "civ_dep_biankouma",
        "Biankouma",
        "civ_tonkpi",
        "Tonkpi",
        "Q4902541",
        7.73333333,
        -7.61666667,
        "Biankouma",
        "u",
        False,
        238714,
    ),
    (
        "civ_dep_danane",
        "Danané",
        "civ_tonkpi",
        "Tonkpi",
        "Q1007988",
        7.26666667,
        -8.16666667,
        "Danané",
        "u",
        False,
        364012,
    ),
    (
        "civ_dep_man",
        "Man",
        "civ_tonkpi",
        "Tonkpi",
        "Q7193694",
        7.4,
        -7.55,
        "Man",
        "u",
        False,
        461135,
    ),
    (
        "civ_dep_sipilou",
        "Sipilou",
        "civ_tonkpi",
        "Tonkpi",
        "Q22080639",
        7.86666667,
        -8.1,
        "Sipilou",
        "u",
        True,
        73109,
    ),
    (
        "civ_dep_zouan_hounien",
        "Zouan-Hounien",
        "civ_tonkpi",
        "Tonkpi",
        "Q3576153",
        6.91666667,
        -8.21666667,
        "Zouan-Hounien",
        "u",
        False,
        250938,
    ),
    (
        "civ_dep_daloa",
        "Daloa",
        "civ_haut_sassandra",
        "Haut-Sassandra",
        "Q5211580",
        6.88333333,
        -6.45,
        "Daloa",
        "u",
        False,
        705378,
    ),
    (
        "civ_dep_issia",
        "Issia",
        "civ_haut_sassandra",
        "Haut-Sassandra",
        "Q6088268",
        6.5,
        -6.5,
        "Issia",
        "u",
        False,
        410628,
    ),
    (
        "civ_dep_vavoua",
        "Vavoua",
        "civ_haut_sassandra",
        "Haut-Sassandra",
        "Q3555128",
        7.38,
        -6.49,
        "Vavoua",
        "u",
        False,
        477154,
    ),
    (
        "civ_dep_zoukougbeu",
        "Zoukougbeu",
        "civ_haut_sassandra",
        "Haut-Sassandra",
        "Q8074642",
        6.76666667,
        -6.86666667,
        "Zoukougbeu",
        "u",
        False,
        146537,
    ),
    (
        "civ_dep_bonon",
        "Bonon",
        "civ_marahoue",
        "Marahoué",
        "Q123278669",
        6.8324,
        -5.9779,
        "Bonon",
        "u",
        False,
        167397,
    ),
    (
        "civ_dep_bouafle",
        "Bouaflé",
        "civ_marahoue",
        "Marahoué",
        "Q4949214",
        6.98333333,
        -5.75,
        "Bouaflé",
        "u",
        False,
        300305,
    ),
    (
        "civ_dep_gohitafla",
        "Gohitafla",
        "civ_marahoue",
        "Marahoué",
        "Q123279235",
        7.5,
        -5.88333333,
        "Gohitafla",
        "u",
        False,
        83370,
    ),
    (
        "civ_dep_sinfra",
        "Sinfra",
        "civ_marahoue",
        "Marahoué",
        "Q968795",
        6.62166667,
        -5.91027778,
        "Sinfra",
        "u",
        False,
        245226,
    ),
    (
        "civ_dep_zuenoula",
        "Zuénoula",
        "civ_marahoue",
        "Marahoué",
        "Q3576317",
        7.42916667,
        -6.04305556,
        "Zuénoula",
        "u",
        False,
        184882,
    ),
    (
        "civ_dep_boundiali",
        "Boundiali",
        "civ_bagoue",
        "Bagoué",
        "Q7193976",
        9.53333333,
        -6.48333333,
        "Boundiali",
        "u",
        False,
        198541,
    ),
    (
        "civ_dep_kouto",
        "Kouto",
        "civ_bagoue",
        "Bagoué",
        "Q6434780",
        9.9,
        -6.41666667,
        "Kouto",
        "u",
        False,
        175587,
    ),
    (
        "civ_dep_tengrela",
        "Tengréla",
        "civ_bagoue",
        "Bagoué",
        "Q3529181",
        10.4869,
        -6.38,
        "Tengréla",
        "u",
        False,
        141761,
    ),
    (
        "civ_dep_dikodougou",
        "Dikodougou",
        "civ_poro",
        "Poro",
        "Q22080778",
        9.06666667,
        -5.76666667,
        "Dikodougou",
        "u",
        False,
        102115,
    ),
    (
        "civ_dep_korhogo",
        "Korhogo",
        "civ_poro",
        "Poro",
        "Q6432251",
        9.41666667,
        -5.61666667,
        "Korhogo",
        "u",
        False,
        748393,
    ),
    (
        "civ_dep_m_bengue",
        "M’Bengué",
        "civ_poro",
        "Poro",
        "Q22080526",
        10.0,
        -5.9,
        "Mbengué",
        "u",
        False,
        114971,
    ),
    (
        "civ_dep_sinematiali",
        "Sinématiali",
        "civ_poro",
        "Poro",
        "Q7525274",
        9.58333333,
        -5.38333333,
        "Sinématiali",
        "u",
        False,
        74981,
    ),
    (
        "civ_dep_ferkessedougou",
        "Ferkessédougou",
        "civ_tchologo",
        "Tchologo",
        "Q5444343",
        9.58333333,
        -5.2,
        "Ferkessédougou",
        "u",
        False,
        190141,
    ),
    (
        "civ_dep_kong",
        "Kong",
        "civ_tchologo",
        "Tchologo",
        "Q22080484",
        9.15,
        -4.61666667,
        "Kong",
        "u",
        False,
        118304,
    ),
    (
        "civ_dep_ouangolodougou",
        "Ouangolodougou",
        "civ_tchologo",
        "Tchologo",
        "Q7110199",
        9.96666667,
        -5.15,
        "Ouangolodougou",
        "u",
        False,
        294639,
    ),
    (
        "civ_dep_beoumi",
        "Béoumi",
        "civ_gbeke",
        "Gbêkê",
        "Q5005056",
        7.66666667,
        -5.58333333,
        "Béoumi",
        "u",
        False,
        195015,
    ),
    (
        "civ_dep_botro",
        "Botro",
        "civ_gbeke",
        "Gbêkê",
        "Q4948792",
        7.85,
        -5.31666667,
        "Botro",
        "u",
        False,
        117924,
    ),
    (
        "civ_dep_bouake",
        "Bouaké",
        "civ_gbeke",
        "Gbêkê",
        "Q4949218",
        7.68333333,
        -5.01666667,
        "Bouaké",
        "d",
        False,
        931851,
    ),
    (
        "civ_dep_sakassou",
        "Sakassou",
        "civ_gbeke",
        "Gbêkê",
        "Q3469360",
        7.447222,
        -5.294444,
        "Sakassou",
        "d",
        False,
        108110,
    ),
    (
        "civ_dep_dabakala",
        "Dabakala",
        "civ_hambol",
        "Hambol",
        "Q3011580",
        8.36666667,
        -4.43333333,
        "Dabakala",
        "u",
        False,
        254430,
    ),
    (
        "civ_dep_katiola",
        "Katiola",
        "civ_hambol",
        "Hambol",
        "Q6377623",
        8.13333333,
        -5.1,
        "Katiola",
        "u",
        False,
        162472,
    ),
    (
        "civ_dep_niakaramandougou",
        "Niakaramandougou",
        "civ_hambol",
        "Hambol",
        "Q22080910",
        8.66666667,
        -5.28333333,
        "Niakaramandougou",
        "u",
        False,
        195127,
    ),
    (
        "civ_dep_koro",
        "Koro",
        "civ_bafing",
        "Bafing",
        "Q6432472",
        8.55,
        -7.46666667,
        "Koro",
        "u",
        False,
        76345,
    ),
    (
        "civ_dep_ouaninou",
        "Ouaninou",
        "civ_bafing",
        "Bafing",
        "Q22080926",
        8.23333333,
        -7.86666667,
        "Ouaninou",
        "u",
        False,
        65981,
    ),
    (
        "civ_dep_touba",
        "Touba",
        "civ_bafing",
        "Bafing",
        "Q7828530",
        8.26667,
        -7.68333,
        "Touba",
        "u",
        False,
        120524,
    ),
    (
        "civ_dep_dianra",
        "Dianra",
        "civ_bere",
        "Béré",
        "Q22080353",
        8.76666667,
        -6.25,
        "Dianra",
        "u",
        False,
        119146,
    ),
    (
        "civ_dep_kounahiri",
        "Kounahiri",
        "civ_bere",
        "Béré",
        "Q6434626",
        7.8,
        -5.83333333,
        "Kounahiri",
        "u",
        False,
        101111,
    ),
    (
        "civ_dep_mankono",
        "Mankono",
        "civ_bere",
        "Béré",
        "Q3286018",
        8.06,
        -6.19,
        "Mankono",
        "d",
        False,
        271894,
    ),
    (
        "civ_dep_kani",
        "Kani",
        "civ_worodougou",
        "Worodougou",
        "Q13125224",
        8.48333333,
        -6.6,
        "Kani",
        "u",
        False,
        131428,
    ),
    (
        "civ_dep_seguela",
        "Séguéla",
        "civ_worodougou",
        "Worodougou",
        "Q8173842",
        7.95694444,
        -6.66805555,
        "Séguéla",
        "u",
        False,
        298384,
    ),
    (
        "civ_dep_bouna",
        "Bouna",
        "civ_bounkani",
        "Bounkani",
        "Q4949789",
        9.26666667,
        -3.0,
        "Bouna",
        "u",
        False,
        178081,
    ),
    (
        "civ_dep_doropo",
        "Doropo",
        "civ_bounkani",
        "Bounkani",
        "Q22080783",
        9.81666667,
        -3.35,
        "Doropo",
        "u",
        False,
        93386,
    ),
    (
        "civ_dep_nassian",
        "Nassian",
        "civ_bounkani",
        "Bounkani",
        "Q6967654",
        8.45,
        -3.46666667,
        "Nassian",
        "u",
        False,
        71724,
    ),
    (
        "civ_dep_tehini",
        "Téhini",
        "civ_bounkani",
        "Bounkani",
        "Q22080985",
        9.6,
        -3.66666667,
        "Téhini",
        "u",
        False,
        83846,
    ),
    (
        "civ_dep_bondoukou",
        "Bondoukou",
        "civ_gontougo",
        "Gontougo",
        "Q1682736",
        8.03333333,
        -2.8,
        "Bondoukou",
        "u",
        False,
        453841,
    ),
    (
        "civ_dep_koun_fao",
        "Koun-Fao",
        "civ_gontougo",
        "Gontougo",
        "Q6434623",
        7.48333333,
        -3.25,
        "Koun-Fao",
        "u",
        False,
        167881,
    ),
    (
        "civ_dep_sandegue",
        "Sandégué",
        "civ_gontougo",
        "Gontougo",
        "Q22080962",
        7.95,
        -3.58333333,
        "Sandégué",
        "u",
        False,
        69742,
    ),
    (
        "civ_dep_tanda",
        "Tanda",
        "civ_gontougo",
        "Gontougo",
        "Q3515006",
        7.8,
        -3.17,
        "Tanda",
        "u",
        False,
        113523,
    ),
    (
        "civ_dep_transua",
        "Transua",
        "civ_gontougo",
        "Gontougo",
        "Q22080994",
        7.55,
        -3.01666667,
        "Transua",
        "u",
        False,
        112842,
    ),
    (
        "civ_dep_abidjan",
        "Abidjan",
        "civ_abidjan",
        "Abidjan (district autonome)",
        "Q4667612",
        5.41667,
        -4.03333,
        "Abidjan",
        "u",
        False,
        6321017,
    ),
    (
        "civ_dep_attiegouakro",
        "Attiégouakro",
        "civ_yamoussoukro",
        "Yamoussoukro (district autonome)",
        "Q23058496",
        6.76666667,
        -5.11666667,
        "Attiégouakro",
        "r",
        False,
        49513,
    ),
    (
        "civ_dep_yamoussoukro",
        "Yamoussoukro",
        "civ_yamoussoukro",
        "Yamoussoukro (district autonome)",
        "Q8048095",
        6.83333,
        -5.25,
        "Yamoussoukro",
        "u",
        False,
        372559,
    ),
)


LOCALITES_SEED: list[dict[str, Any]] = [
    # ===== Continent (1) =====
    {
        "code": "afrique",
        "nom": "Afrique",
        "type_localite": "continent",
        "parent_code": None,
        "pays_iso3": None,
        "latitude": None,
        "longitude": None,
        "altitude_metres": None,
        "population_estimee": 1_515_140_849,
        "annee_population": 2024,
        "fuseau_horaire": None,
        "notes": (
            "Population UN World Population Prospects 2024 (medium-fertility variant), "
            "date de référence 2024-07-01. Coordonnées centroid non renseignées : entité "
            "structurelle racine. Wikidata Q15. Source : https://population.un.org/wpp/."
        ),
    },
    # ===== Pays (1) =====
    {
        "code": "civ",
        "nom": "Côte d'Ivoire",
        "type_localite": "pays",
        "parent_code": "afrique",
        "pays_iso3": "CIV",
        "latitude": 8.0,
        "longitude": -6.0,
        "altitude_metres": None,
        "population_estimee": 29_389_150,
        "annee_population": 2021,
        "fuseau_horaire": "Africa/Abidjan",
        "notes": (
            "Code ISO 3166-1 alpha-3 : CIV. Capitale politique : Yamoussoukro ; "
            "capitale économique : Abidjan. Fuseau UTC+00:00 (Africa/Abidjan). "
            "Centroïde : point représentatif Wikidata Q1008 (P625, rang normal ; "
            "valeur grossière arrondie au degré). Population nationale RGPH 2021 "
            "(INS Côte d'Ivoire) : 29 389 150 hab. — chiffre officiel absent de "
            "Wikidata (P1082 s'arrête à 2017 puis 2023), recoupé par la somme des "
            "14 districts (29 389 152, écart d'arrondi +2). Altitude non renseignée "
            "(pas d'altitude ponctuelle univoque pour un pays)."
        ),
    },
    # ===== Districts (14 : 12 districts + 2 districts autonomes), ISO 3166-2:CI =====
    # Coordonnées : Wikidata P625 (QID cité) ; population : RGPH 2021 (INS).
    _district(
        "civ_abidjan",
        "Abidjan",
        "CI-AB",
        5.33333333,
        -4.01666667,
        6_321_017,
        "Abidjan",
        "Q19830972",
        autonome=True,
    ),
    _district(
        "civ_bas_sassandra",
        "Bas-Sassandra",
        "CI-BS",
        4.751389,
        -6.638611,
        2_687_176,
        "San-Pédro",
        "Q20980352",
    ),
    _district(
        "civ_comoe", "Comoé", "CI-CM", 6.73333333, -3.48333333, 1_501_336, "Abengourou", "Q16629374"
    ),
    _district(
        "civ_denguele", "Denguélé", "CI-DN", 9.5, -7.41699982, 436_015, "Odienné", "Q20980374"
    ),
    _district(
        "civ_goh_djiboua",
        "Gôh-Djiboua",
        "CI-GD",
        6.13333333,
        -5.93333333,
        2_088_440,
        "Gagnoa",
        "Q21003640",
    ),
    _district("civ_lacs", "Lacs", "CI-LC", 6.65, -4.7, 1_488_531, "Dimbokro", "Q20980363"),
    _district(
        "civ_lagunes", "Lagunes", "CI-LG", 5.93333333, -4.21666667, 2_042_623, "Dabou", "Q20980365"
    ),
    _district("civ_montagnes", "Montagnes", "CI-MG", 7.4, -7.55, 3_027_023, "Man", "Q20980366"),
    _district(
        "civ_sassandra_marahoue",
        "Sassandra-Marahoué",
        "CI-SM",
        6.88333333,
        -6.45,
        2_720_877,
        "Daloa",
        "Q20365127",
    ),
    _district(
        "civ_savanes",
        "Savanes",
        "CI-SV",
        9.41666667,
        -5.61666667,
        2_159_435,
        "Korhogo",
        "Q21002161",
    ),
    _district(
        "civ_vallee_du_bandama",
        "Vallée du Bandama",
        "CI-VB",
        8.13333333,
        -5.1,
        1_964_929,
        "Bouaké",
        "Q21002356",
    ),
    _district("civ_woroba", "Woroba", "CI-WR", 8.48333333, -6.6, 1_184_813, "Séguéla", "Q20980371"),
    _district(
        "civ_yamoussoukro",
        "Yamoussoukro",
        "CI-YM",
        6.81667,
        -5.28333,
        422_072,
        "Yamoussoukro",
        "Q19830973",
        autonome=True,
    ),
    _district(
        "civ_zanzan", "Zanzan", "CI-ZZ", 8.61666667, -3.15, 1_344_865, "Bondoukou", "Q21003689"
    ),
    # ===== Régions (31 : niveau générique prefecture), parent = district (ADR-0005) =====
    *(_region(*_r) for _r in _REGIONS_DATA),
    # ===== Départements (111 : niveau commune), parent = région ou district autonome =====
    *(_departement(*_d) for _d in _DEPARTEMENTS_DATA),
]


assert len(LOCALITES_SEED) == 158, (
    f"Attendu 158 localités (1 continent + 1 pays + 14 districts + 31 régions "
    f"+ 111 départements), obtenu {len(LOCALITES_SEED)}"
)

_codes_seen: set[str] = set()
for _entry in LOCALITES_SEED:
    _code = _entry["code"]
    assert _code not in _codes_seen, f"Code dupliqué dans LOCALITES_SEED : {_code!r}"
    _codes_seen.add(_code)
del _codes_seen, _entry, _code
